default[:mysql][:user] = 'root'
default[:mysql][:password] = ''
default[:mysql][:database] = 'test'
default[:mysql][:password] = ''
default[:phpmyadmin][:auth]='cookie'
default[:phpmyadmin][:host]='localhost'
default[:phpmyadmin][:connect_type]='tcp'
default[:phpmyadmin][:allow_password]='true'
